### ISSUE TITLE
math: sign with unexpected inputs

### ISSUE THREAD

**Issue by Bilal2453** [truemedian/lua-extensions#11]
- sign should probably do type checking so it does not return `0` on say strings.

- sign should check for `NaN` so it does not return `0` when it is not actually that.

Could be simply made:

```lua
function ext_math.sign(n)
	if n > 0 then
		return 1
	elseif n < 0 then
		return -1
	elseif n == 0 then
		return 0
	end
end
```

**Comment by Bilal2453** [comment]
@truemedian Should this be closed as resolved in accordance to https://github.com/truemedian/lua-extensions/commit/4eb4f8d4a8353dfd2f1042b2ef198bc70d921195? this [line](https://github.com/truemedian/lua-extensions/commit/4eb4f8d4a8353dfd2f1042b2ef198bc70d921195#diff-709f429c251192caf7c5ed3ecf3aea72bccbce187c7c7a7a2ab799ef82f5fdf6R59) specifically

**Comment by truemedian** [comment]
likely
