### ISSUE TITLE
define the exact behavior of table.shift

### ISSUE THREAD

**Issue by Bilal2453** [truemedian/lua-extensions#25]
What should happen when a negative count is passed?  Currently it is vague to me, and the behavior I may expect is not what happens.  Instead the current behavior is:

```lua
local tbl = {1, 2, 3, 4, 5}
table.shift(tbl, 4, -2)
```
outputs:
```lua
{
  [1] = 1,
  [2] = 4,
  [3] = 5,
  [4] = 4,
  [5] = 5,
}
```
Or an error should be raised for those inputs if not documented.

**Comment by Bilal2453** [comment]
Probably worth noting `0` as well.

**Comment by Bilal2453** [comment]
And what should happen with float inputs? 
(the expected behavior should be documented, or an error should be raised)

**Comment by truemedian** [comment]
A right shift by a negative amount is a left shift by the absolute value of that amount. If the offset is not an integer (like 4.5) then it will behave as if the number were rounded up.

I will change the wording slightly to indicate that everything above and including `index` is what is shifted, which makes the behavior with floating numbers more obvious
