### ISSUE TITLE
math.approxeqrel not accurate enough

### ISSUE THREAD

**Issue by Bilal2453** [truemedian/lua-extensions#6]
Trying to do `math.approxeqrel(math.root(-64, 3), -4)` yields `false`.

On [line 142](https://github.com/truemedian/lua-extensions/blob/master/libs/math.lua#L142) it seems like it was suppose to be:

```lua
tolerance = tolerance or math.sqrt(ext_math.epsilon)
```

On [line 149](https://github.com/truemedian/lua-extensions/blob/master/libs/math.lua#L149) shouldn't the comparison be `<=`, just in case?

Printing out the left and right half of the comparison with the above example yields:
`math.abs(a - b): 4.4408920985006e-16`
`math.max(a, b) * tolerance: -8.8817841970013e-16`

I suppose line 149 should be:
```lua
return math.abs(a - b) <= math.abs(math.max(a, b)) * tolerance
```
which seems to work, in this example at least

**Comment by truemedian** [comment]
Fixed with d23d486
