### ISSUE TITLE
math: approxeqabs failing

### ISSUE THREAD

**Issue by Bilal2453** [truemedian/lua-extensions#8]
`approxeqabs(1 + (1 * math.epsilon), 1)` is returning `false` when it seems like it should be true.  See [the equivalent Zig test](https://github.com/ziglang/zig/blob/master/lib/std/math.zig#L187).

Haven't looked into this one just yet but it seems fairly identical to the Zig code, assuming `@fabs` is doing what I am expecting it does.

~~P.S. the comparison in approxeqabs should be `<=` not `<` as well.~~

Oops, seems like that `<` comparison was actually the cause, I thought it wasn't because I ran the wrong test.

**Comment by truemedian** [comment]
Fixed with 5f4c3e727e813df44325dc62e3062ca0da35f3ae
